# Generated by Django 5.1.7 on 2025-03-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcast2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast2',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts2', to='podcast2.category2'),
        ),
        migrations.AddField(
            model_name='podcast2',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_podcasts2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast2',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_podcasts2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment2',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='podcast2.podcast2'),
        ),
        migrations.AddField(
            model_name='podcaster2profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcaster2_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast2',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts2', to='podcast2.podcaster2profile'),
        ),
    ]
