# Generated by Django 5.1.7 on 2025-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
