# Generated by Django 5.1.7 on 2025-03-17 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='podcasterprofile',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='podcasterprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='podcasterprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='podcasterprofile',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='podcasterprofile',
            name='topics',
        ),
        migrations.AddField(
            model_name='podcast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='podcasterprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podcasterprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='podcasterprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podcast_images/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='podcasterprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podcasterprofile',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to='podcasts.category'),
        ),
    ]
