# Generated by Django 5.1.7 on 2025-03-10 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_expertprofile'),
        ('users', '0002_remove_customuser_is_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to='users.userprofile'),
        ),
    ]
