# Generated by Django 5.1.7 on 2025-03-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_podcasterprofile_alter_podcast_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
