# Generated by Django 5.1.7 on 2025-03-17 23:03

from django.db import migrations
from django.utils.text import slugify

def add_initial_categories(apps, schema_editor):
    Category = apps.get_model('podcasts', 'Category')
    categories = [
        {'name': 'Technology', 'description': 'Tech news, reviews, and discussions'},
        {'name': 'Business', 'description': 'Business news, entrepreneurship, and finance'},
        {'name': 'Science', 'description': 'Scientific discoveries and discussions'},
        {'name': 'Health & Wellness', 'description': 'Health, fitness, and mental wellness'},
        {'name': 'Education', 'description': 'Educational content and learning'},
        {'name': 'Entertainment', 'description': 'Movies, TV shows, and pop culture'},
        {'name': 'News & Politics', 'description': 'Current events and political discussions'},
        {'name': 'Sports', 'description': 'Sports news, analysis, and commentary'},
        {'name': 'Music', 'description': 'Music reviews, interviews, and industry news'},
        {'name': 'Arts & Culture', 'description': 'Art, literature, and cultural topics'},
        {'name': 'History', 'description': 'Historical events and stories'},
        {'name': 'True Crime', 'description': 'True crime stories and investigations'},
        {'name': 'Comedy', 'description': 'Comedy shows and humor'},
        {'name': 'Society', 'description': 'Social issues and cultural commentary'},
        {'name': 'Religion & Spirituality', 'description': 'Religious and spiritual content'},
        {'name': 'Family & Kids', 'description': 'Family-friendly and children\'s content'},
        {'name': 'Food & Cooking', 'description': 'Cooking tips, recipes, and food culture'},
        {'name': 'Travel', 'description': 'Travel stories, tips, and destinations'},
        {'name': 'Personal Development', 'description': 'Self-improvement and motivation'},
        {'name': 'Career', 'description': 'Career advice and professional development'}
    ]
    
    for category_data in categories:
        name = category_data['name']
        category_data['slug'] = slugify(name)
        Category.objects.create(**category_data)

def remove_categories(apps, schema_editor):
    Category = apps.get_model('podcasts', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_category_alter_podcast_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_categories, remove_categories),
    ]
