# Generated by Django 5.1.7 on 2025-03-20 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_add_initial_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_podcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_podcasts', to=settings.AUTH_USER_MODEL),
        ),
    ]
