# Generated by Django 5.1.7 on 2025-03-17 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcasterprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='podcasterprofile',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='podcasterprofile',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='podcasterprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='podcasterprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='podcasterprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podcasterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
