# Generated by Django 5.1.7 on 2025-03-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_podcastreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastreaction',
            name='updated_at',
        ),
    ]
