# Generated by Django 5.1.7 on 2025-03-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_alter_podcast_category'),
        ('podcasts', '0012_remove_reactions'),
    ]

    operations = [
    ]
