# Generated by Django 5.1.7 on 2025-03-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0013_merge_20250329_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
