# Generated by Django 5.1.7 on 2025-03-10 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborations', '0001_initial'),
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.podcast'),
        ),
    ]
