# Generated by Django 5.1.7 on 2025-03-17 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_experts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='viewed_experts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExpertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='experts.expertprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.expertprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('expert', 'user')},
            },
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='ratings',
            field=models.ManyToManyField(related_name='rated_experts', through='experts.ExpertRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
