# Generated by Django 5.1.7 on 2025-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='expert_profiles/'),
        ),
    ]
