# Generated by Django 5.1.7 on 2025-04-15 12:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='total_bookmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
