# Generated by Django 5.1.7 on 2025-03-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='cover_image',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='title',
        ),
        migrations.AddField(
            model_name='expert',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='expert',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expert',
            name='expertise',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='expert',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='expert',
            name='social_media',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
