# Generated by Django 5.1.7 on 2025-03-20 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_expertprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_experts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_experts', to=settings.AUTH_USER_MODEL),
        ),
    ]
