# Generated by Django 5.1.7 on 2025-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_add_updated_at_to_expertreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertprofile',
            name='ratings',
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
