# Generated by Django 5.1.7 on 2025-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_expertprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Expert Categories',
            },
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='categories',
            field=models.ManyToManyField(related_name='experts', to='experts.expertcategory'),
        ),
    ]
