# Generated by Django 5.1.7 on 2025-08-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_remove_expertprofile_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email for this expert', max_length=254, null=True),
        ),
    ]
