# Generated by Django 5.1.7 on 2025-03-20 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_expertprofile_dislikes_expertprofile_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertcomment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_expert_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_expert_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
