# Generated by Django 5.1.7 on 2025-04-11 00:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_expertprofile_updated_at_alter_expertprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='verification_documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='expertise',
            field=models.TextField(),
        ),
    ]
