# Generated by Django 5.1.7 on 2025-03-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='expertcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='experts.expertcomment'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
