# Generated by Django 5.1.7 on 2025-03-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0008_expertreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertreaction',
            name='updated_at',
        ),
    ]
